'\" t
.\"     Title: \fBktouch\fR
.\"    Author: Ben Burton <bab@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-11-02
.\"    Manual: KTouch anv\(:andarhandbok
.\"    Source: KDE-program KTouch 2.3.0 (Program 16.12)
.\"  Language: Swedish
.\"
.TH "\FBKTOUCH\FR" "1" "2016\-11\-02" "KDE-program KTouch 2.3.0 (Prog" "KTouch anv\(:andarhandbok"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAMN"
ktouch \- Ett program f\(:or att l\(:ara sig maskinskrivning av KDE
.SH "SYNOPSIS"
.HP \w'\fBktouch\fR\ 'u
\fBktouch\fR [\fB\-\-resource\-editor\fR] [\fB\-I \-\-import\-path\fR\fIs\(:okv\(:ag\fR]
.SH "BESKRIVNING"
.PP
KTouch
\(:ar ett program f\(:or att l\(:ara sig maskinskrivning\&. Det hj\(:alper dig att skriva snabbt och korrekt p\(oa ett tangentbord\&. Varje finger har sin plats p\(oa tangentbordet med tillh\(:orande tangenter att trycka ner\&.
.PP
KTouch
hj\(:alper dig att l\(:ara dig skriva maskin genom att tillhandah\(oalla en text att \(:ova p\(oa, och justeras till olika niv\(oaer, beroende p\(oa hur bra du \(:ar\&. Det visar vilken tangent som ska tryckas ner h\(:arn\(:ast, och det riktiga fingret som ska anv\(:andas\&.
.PP
Programmet \(:ar en del av
KDE:s officiella utbildningsmodul\&.
.SH "KTOUCH\-V\(:ALJARE"
.PP
\fB\-\-resource\-editor\fR
.RS 4
Starta kurs\- och tangentbordslayouteditorn\&.
.RE
.PP
\fB\-I \-\-import\-path\fR \fIs\(:okv\(:ag\fR
.RS 4
L\(:agg till s\(:okv\(:agen f\(:orst i listan \(:over QML\-imports\(:okv\(:agar\&.
.RE
.SH "SE OCKS\(oA"
.RS 4
Mer detaljerad anv\(:andardokumentation \(:ar tillg\(:anglig med \m[blue]\fBhelp:/ktouch\fR\m[] (skriv antingen in webbadressen i Konqueror, eller k\(:or \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/ktouch\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Det finns ocks\(oa ytterligare information tillg\(:anglig p\(oa \m[blue]\fBwebbsidan f\(:or KDE:s utbildningsprojekt\fR\m[]\&\s-2\u[1]\d\s+2\&.
.RE
.SH "UPPHOVSM\(:AN"
.PP
KTouch \(:ar skrivet av
Haavard Froeiland
<haavard@users\&.sourceforge\&.net>
och
Andreas Nicolai
<Andreas\&.Nicolai@gmx\&.net>\&. Den h\(:ar manualsidan \(:ar baserad p\(oa den som tagits fram f\(:or Debian av
Ben Burton\&.
.SH "AUTHOR"
.PP
\fBBen Burton\fR <\&bab@debian\&.org\&>
.RS 4
Ktouch manualsida\&.
.RE
.SH "NOTER"
.IP " 1." 4
webbsidan f\(:or KDE:s utbildningsprojekt
.RS 4
\%http://edu.kde.org/ktouch/
.RE
