'\" t
.\"     Title: \fBktouch\fR
.\"    Author: Ben Burton <bab@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-11-02
.\"    Manual: KTouch-Benutzerhandbuch
.\"    Source: KDE-Anwendungen KTouch 2.3.0 (Anwendungen 16.12)
.\"  Language: German
.\"
.TH "\FBKTOUCH\FR" "1" "2016\-11\-02" "KDE-Anwendungen KTouch 2.3.0 (" "KTouch-Benutzerhandbuch"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ktouch \- Ein Schreibmaschinenkurs von KDE
.SH "\(:UBERSICHT"
.HP \w'\fBktouch\fR\ 'u
\fBktouch\fR [\fB\-\-resource\-editor\fR] [\fB\-I \-\-import\-path\fR\fIpath\fR]
.SH "BESCHREIBUNG"
.PP
KTouch
ist ein Programm, um das Maschineschreiben zu lernen\&. Sie lernen schnell und richtig auf der Tastatur zu schreiben\&. Jeder Finger hat einen bestimmten Platz auf der Tastatur und soll die zugeh\(:origen Tasten dr\(:ucken\&.
.PP
KTouch
unterst\(:utzt Sie beim Lernen des Maschineschreibens mit \(:Ubungstexten in verschiedenen Schwierigkeitsstufen\&. Das Programm zeigt Ihnen die Taste an, die als N\(:achste gedr\(:uckt werden muss, und auch welchen Finger Sie daf\(:ur benutzen sollen\&.
.PP
Dieses Programm ist Teil der offiziellen
KDE\-Lernprogramme\&.
.SH "KTOUCH\-OPTIONEN"
.PP
\fB\-\-resource\-editor\fR
.RS 4
Startet den Kurs\- und Tastaturbelegungseditor\&.
.RE
.PP
\fB\-I \-\-import\-path\fR \fIpath\fR
.RS 4
Diesen Pfad der Liste der QML\-Import\-Pfade voranstellen\&.
.RE
.SH "SIEHE AUCH"
.RS 4
Weitere ausf\(:uhrliche Dokumentation finden Sie unter \m[blue]\fBhelp:/ktouch\fR\m[] (geben Sie diese URL entweder im Konqueror ein oder starten Sie \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/ktouch\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Weitere Informationen finden Sie auf der \m[blue]\fBKDE \-Edu\-Webseite\fR\m[]\&\s-2\u[1]\d\s+2\&.
.RE
.SH "AUTOREN"
.PP
KTouch wurde von
Haavard Froeiland
<haavard@users\&.sourceforge\&.net>
und
Andreas Nicolai
<Andreas\&.Nicolai@gmx\&.net>
geschrieben\&. Diese Handbuchseite wurde auf der Grundlage des von
Ben Burton
f\(:ur das Debian\-Projekt geschriebenen Handbuchs erstellt\&.
.SH "AUTOR"
.PP
\fBBen Burton\fR <\&bab@debian\&.org\&>
.RS 4
Benutzerhandbuch f\(:ur KTouch
.RE
.SH "FU\(ssNOTEN"
.IP " 1." 4
 KDE -Edu-Webseite
.RS 4
\%http://edu.kde.org/ktouch/
.RE
