'\" t
.\"     Title: \fBktouch\fR
.\"    Author: Ben Burton <bab@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2012-11-18
.\"    Manual: Manuale utente di KDE
.\"    Source: Ambiente desktop KDE
.\"  Language: Italian
.\"
.TH "\FBKTOUCH\FR" "1" "2012\-11\-18" "Ambiente desktop KDE" "Manuale utente di KDE"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOME"
ktouch \- un istruttore di dattilografia per KDE
.SH "SINOSSI"
.HP \w'\fBktouch\fR\ 'u
\fBktouch\fR [\fBURL\fR] [opzioni\ generiche\ di\ KDE] [opzioni\ generiche\ di\ Qt] [opzioni\ di\ KTouch]
.SH "DESCRIZIONE"
.PP
KTouch
\(`e un programma per imparare la dattilografia\&. Ti aiuta a scrivere velocemente e senza errori con la tastiera\&. Ogni dito ha il proprio posto sulla tastiera, con i relativi tasti da premere\&.
.PP
KTouch
ti aiuta a dattilografare fornendoti del testo con cui esercitarti, e sceglie il livello adatto alle tue capacit\(`a\&. Pu\(`o mostrati il prossimo tasto da premere e il dito corretto da usare\&.
.PP
Questa applicazione fa parte del modulo ufficiale
KDE
Edu\&.
.SH "OPZIONI DI KTOUCH"
.PP
\fB\-\-opengl\fR
.RS 4
Usa QGLWidget per l\*(Aqarea di visualizzazione\&.
.RE
.PP
\fB\-\-resource\-editor\fR
.RS 4
Avvia l\*(Aqeditor di corsi e mappature di tastiera\&.
.RE
.SH "VEDI ANCHE"
.PP
\(`E possibile ottenere documentazione pi\(`u dettagliata tramite
\m[blue]\fBhelp:/ktouch\fR\m[]
(inserisci questo
URL
in
Konqueror, o esegui
\fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/ktouch\fR\fR)\&.
.PP
Maggiori informazioni sono disponibili anche presso il
\m[blue]\fBsito web KDE Edu\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTORI"
.PP
KTouch \(`e stato scritto da
Haavard Froeiland
<haavard@users\&.sourceforge\&.net>
e
Andreas Nicolai
<Andreas\&.Nicolai@gmx\&.net>\&. Questa pagina di manuale \(`e basata su quella scritta per Debian da
Ben Burton
.SH "AUTORE"
.PP
\fBBen Burton\fR <\&bab@debian\&.org\&>
.RS 4
Pagina di man di KTouch\&.
.RE
.SH "NOTE"
.IP " 1." 4
sito web KDE Edu
.RS 4
\%http://edu.kde.org/ktouch/
.RE
