'\" t
.\"     Title: \fBktouch\fR
.\"    Author: Ben Burton <bab@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2 листопада 2016 року
.\"    Manual: Інструкція користувача KTouch
.\"    Source: Програми KDE KTouch 2.3.0 (Програми 16.12)
.\"  Language: Ukrainian
.\"
.TH "\fBktouch\fR" "1" "2 листопада 2016 року" "Програми KDE KTouch 2.3.0 (Про" "Інструкція користувача KTouch"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
ktouch \- інструктор з навчання друку KDE
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBktouch\fR\ 'u
\fBktouch\fR [\fB\-\-resource\-editor\fR] [\fB\-I \-\-import\-path\fR\fIшлях\fR]
.SH "ОПИС"
.PP
KTouch
\(em це програма для навчання друку наосліп\&. Вона допоможе вам навчитися друкувати на клавіатурі швидко і правильно\&. Ця програма підкаже вам, де має знаходитися кожен з пальців на клавіатурі і клавіші, які слід натискати цим пальцем\&.
.PP
KTouch
проводить навчання друку наосліп за допомогою тренувальних текстів і змінює рівень їх складності залежно від вашої вправності\&. Програма може показувати вам, яку клавішу слід натискати наступною, і який палець для цього слід використати\&.
.PP
Ця програма є частиною офіційного освітнього модуля
KDE\&.
.SH "ПАРАМЕТРИ KTouch"
.PP
\fB\-\-resource\-editor\fR
.RS 4
Запустити редактор курсів навчання та розкладок клавіатури\&.
.RE
.PP
\fB\-I \-\-import\-path\fR \fIшлях\fR
.RS 4
Дописати шлях на початку списку шляхів імпортування QML\&.
.RE
.SH "ПРОЧИТАЙТЕ ТАКОЖ"
.RS 4
Детальнішу інформацію для користувача можна знайти за адресою \m[blue]\fBhelp:/ktouch\fR\m[] (або введіть цю адресу URL у поле адреси Konqueror, або виконайте команду \fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/ktouch\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Подальшу інформацію можна отримати на \m[blue]\fBсайті освітнього модуля KDE\fR\m[]\&\s-2\u[1]\d\s+2\&.
.RE
.SH "АВТОРИ"
.PP
KTouch було написано
Haavard Froeiland
<haavard@users\&.sourceforge\&.net>
and
Andreas Nicolai
<Andreas\&.Nicolai@gmx\&.net>\&. Ця сторінка довідника заснована на сторінці підготованій для проекту Debian
Ben Burton
.SH "АВТОР"
.PP
\fBBen Burton\fR <\&bab@debian\&.org\&>
.RS 4
Сторінка довідника (man) для KTouch\&.
.RE
.SH "ПРИМІТКИ"
.IP " 1." 4
сайті освітнього модуля KDE
.RS 4
\%http://edu.kde.org/ktouch/
.RE
