'\" t
.\"     Title: \fBktouch\fR
.\"    Author: Ben Burton <bab@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-11-02
.\"    Manual: Manual del usuario de KTouch
.\"    Source: Aplicaciones de KDE KTouch 2.3.0 (Aplicaciones 16.12)
.\"  Language: Spanish
.\"
.TH "\FBKTOUCH\FR" "1" "2016\-11\-02" "Aplicaciones de KDE KTouch 2.3" "Manual del usuario de KTouch"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOMBRE"
ktouch \- un tutor de mecanograf\('ia creado por KDE
.SH "SINOPSIS"
.HP \w'\fBktouch\fR\ 'u
\fBktouch\fR [\fB\-\-resource\-editor\fR] [\fB\-I \-\-import\-path\fR\fIruta\fR]
.SH "DESCRIPCI\('ON"
.PP
KTouch
es un programa para aprender mecanograf\('ia\&. Le ayudar\('a a aprender a mecanografiar en un teclado de forma r\('apida y correcta\&. Cada dedo tiene su lugar en el teclado con teclas asociadas para pulsar\&.
.PP
KTouch
le ayuda a aprender mecanograf\('ia proporcion\('andole un texto de entrenamiento, y a ajustar diferentes niveles dependiendo de lo bueno que sea\&. Puede mostrar qu\('e tecla pulsar a continuaci\('on y corregir el dedo a utilizar\&.
.PP
Esta aplicaci\('on es parte del m\('odulo educativo oficial de
KDE\&.
.SH "OPCIONES DE KTOUCH"
.PP
\fB\-\-resource\-editor\fR
.RS 4
Lanza el editor del curso y de la distribuci\('on del teclado\&.
.RE
.PP
\fB\-I \-\-import\-path\fR \fIruta\fR
.RS 4
Usar la ruta como prefijo de la lista de rutas de importaci\('on de QML\&.
.RE
.SH "VEA TAMBI\('EN"
.RS 4
Existe documentaci\('on m\('as detallada disponible en \m[blue]\fBhelp:/ktouch\fR\m[] (bien introduciendo la URL en Konqueror o ejecutando \fB\fBkhelpcenter\fR\fR\fB\fIhelp:/ktouch\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Existe informaci\('on m\('as amplia disponible en el \m[blue]\fBsitio web de KDE educativo\fR\m[]\&\s-2\u[1]\d\s+2\&.
.RE
.SH "AUTORES"
.PP
KTouch fue escrito por
Haavard Froeiland
<haavard@users\&.sourceforge\&.net>
y
Andreas Nicolai
<Andreas\&.Nicolai@gmx\&.net>\&. Esta p\('agina de manual est\('a basada en una preparada para Debian por
Ben Burton
.SH "AUTOR"
.PP
\fBBen Burton\fR <\&bab@debian\&.org\&>
.RS 4
KTouch man page\&.
.RE
.SH "NOTAS"
.IP " 1." 4
sitio web de KDE educativo
.RS 4
\%http://edu.kde.org/ktouch/
.RE
