'\" t
.\"     Title: \fBktouch\fR
.\"    Author: Burton, Ben <bab@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2 de novembre de 2016
.\"    Manual: Manual d'usuari del KTouch
.\"    Source: Aplicacions KDE KTouch 2.3.0 (Aplicacions 16.12)
.\"  Language: Catalan
.\"
.TH "\FBKTOUCH\FR" "1" "2 de novembre de 2016" "Aplicacions KDE KTouch 2.3.0 (" "Manual d'usuari del KTouch"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
ktouch \- un tutor de mecanografia creat per la comunitat KDE
.SH "SINOPSI"
.HP \w'\fBktouch\fR\ 'u
\fBktouch\fR [\fB\-\-resource\-editor\fR] [\fB\-I \-\-import\-path\fR\fIcam\('i\fR]
.SH "DESCRIPCI\('O"
.PP
KTouch
\('es un programa per aprendre a mecanografiar\&. Us ajuda a escriure sobre un teclat de manera r\(`apida i correcta\&. Cada dit t\('e el seu lloc sobre el teclat amb la tecla associada corresponent a pr\('emer\&.
.PP
KTouch
us ajuda a aprendre a mecanografiar proveint\-vos el text sobre el qual entrenar, i s\*(Aqajusta a diferents nivells depenent de la vostra destresa\&. Tamb\('e pot mostrar quina \('es la seg\(:uent tecla a mostrar, i el dit correcte a usar\&.
.PP
Aquesta aplicaci\('o forma part del m\(`odul educatiu oficial del
KDE\&.
.SH "OPCIONS DEL KTOUCH"
.PP
\fB\-\-resource\-editor\fR
.RS 4
Llan\(,ca l\*(Aqeditor de curs i disposici\('o del teclat\&.
.RE
.PP
\fB\-I \-\-import\-path\fR \fIcam\('i\fR
.RS 4
Anteposa el cam\('i a la llista de camins d\*(Aqimportaci\('o del QML\&.
.RE
.SH "VEGEU TAMB\('E"
.RS 4
Hi ha disponible documentaci\('o d\*(Aqusuari m\('es detallada des de \m[blue]\fBhelp:/ktouch\fR\m[] (introdu\(:iu aquest URL al Konqueror o executeu \fB\fBkhelpcenter\fR\fR\fB\fIhelp:/ktouch\fR\fR)\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.RS 4
Tamb\('e hi ha m\('es informaci\('o disponible al \m[blue]\fBlloc web del KDE Education\fR\m[]\&\s-2\u[1]\d\s+2\&.
.RE
.SH "AUTORS"
.PP
KTouch fou escrit per en
Froeiland, Haavard
<haavard@users\&.sourceforge\&.net>
i
Nicolai, Andreas
<Andreas\&.Nicolai@gmx\&.net>\&. Aquesta p\(`agina de manual es basa en una preparada per a Debian per en
Burton, Ben\&.
.SH "AUTOR"
.PP
\fBBurton, Ben\fR <\&bab@debian\&.org\&>
.RS 4
P\(`agina man de KTouch\&.
.RE
.SH "NOTES"
.IP " 1." 4
lloc web del KDE Education
.RS 4
\%http://edukdeorg/ktouch/
.RE
